version: '3.1'

services:
  mariadb:
    image: mariadb:11.2
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: orderize
      MARIADB_USER: client
      MARIADB_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - connection_back_db

  backend_1:
    image: santthiago/orderize-backend:latest
    container_name: backend_1
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/orderize
      SPRING_DATASOURCE_USERNAME: client
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8081:8080"
    depends_on:
      - mariadb
    restart: on-failure:10
    networks:
      - connection_back_db

  backend_2:
    image: santthiago/orderize-backend:latest
    container_name: backend_2
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/orderize
      SPRING_DATASOURCE_USERNAME: client
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8082:8080"
    depends_on:
      - mariadb
    restart: on-failure:10
    networks:
      - connection_back_db

  backend_3:
    image: santthiago/orderize-backend:latest
    container_name: backend_3
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/orderize
      SPRING_DATASOURCE_USERNAME: client
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8083:8080"
    depends_on:
      - mariadb
    restart: on-failure:10
    networks:
      - connection_back_db


volumes:
  mariadb_data:

networks:
  connection_back_db: