version: '3.1'

services:
  mariadb:
    image: mariadb:11.2
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: orderize
      MARIADB_USER: client
      MARIADB_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql


volumes:
  mariadb_data:


