version: '3.1'

services: 
  frontend:
    image: santthiago/orderize-site:0.0.1
    container_name: frontend
    ports:
      - "80:80"
      # depends_on:
      # - backend
      # networks:
      # - connection_front_back
      # volumes:
      # mariadb_data:
      # networks:
      # connection_back_db:
      # connection_front_back:
